CREATE TABLE Links (
  user_id MEDIUMINT UNSIGNED NOT NULL,
  type VARCHAR(30) NOT NULL,
  url TEXT NOT NULL,
  PRIMARY KEY (user_id, type),
  FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
